/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElC: typeof import('element-plus/es')['ElC']
  const ElDiv: typeof import('element-plus/es')['ElDiv']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElSpan: typeof import('element-plus/es')['ElSpan']
}
