/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBtton: typeof import('element-plus/es')['ElBtton']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConatiner: typeof import('element-plus/es')['ElConatiner']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElCrollbar: typeof import('element-plus/es')['ElCrollbar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDiv: typeof import('element-plus/es')['ElDiv']
    ElDivi: typeof import('element-plus/es')['ElDivi']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElF: typeof import('element-plus/es')['ElF']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    'ElForm-': typeof import('element-plus/es')['ElForm-']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpac: typeof import('element-plus/es')['ElSpac']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSpan: typeof import('element-plus/es')['ElSpan']
    ElText: typeof import('element-plus/es')['ElText']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeFooter: typeof import('./src/components/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    HomeLeftAside: typeof import('./src/components/HomeLeftAside.vue')['default']
    HomeMain: typeof import('./src/components/HomeMain.vue')['default']
    Main: typeof import('./src/components/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
